server:
  port: 7206
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7201/eureka
management:
  tracing:
    sampling:
      probability: 1.0
spring:
  application:
    name: apigateway
  config:
    import: "optional:configserver:http://localhost:7200"
  cloud:
    gateway:
      mvc:
        routes:
          - id: employeeservice
            uri: lb://employeeservice
            predicates:
              - Path=/employees/**
          - id: taskservice
            uri: lb://taskservice
            predicates:
              - Path=/tasks/**
          - id: taskdetailservice
            uri: lb://taskdetail
            predicates:
              - Path=/taskdetail/**
          - id: notificationservice
            uri: lb://notificationservice
            predicates:
              - Path=/notification/**