server:
  port: 7202

spring:
  application:
    name: employeeservice
  boot:
    admin:
      client:
        url: http://localhost:7207
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7201/eureka

management:
  endpoints.web.exposure.include:
    - '*'
  tracing:
    sampling:
      probability: 1.0