server:
  port: 7201

spring:
  application:
    name: eurekaserver
  boot:
    admin:
      client:
        url: http://localhost:7207

management:
  endpoints.web.exposure.include:
    - '*'
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7201/eureka