server:
  port: 7204


spring:
  application:
    name: notificationservice

  datasource:
    username: postgres
    password: '1234'
    url: jdbc:postgresql://localhost:5432/TaskDB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: hibbaan
    password: hibbaan
    port: '5672'
    host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7201/eureka

ms:
  rabbit:
    exchange:
      name: myexchange
    queue:
      name: myqueue
    routing:
      name: myrouting
management:
  endpoints.web.exposure.include:
    - '*'
  tracing:
    sampling:
      probability: 1.0