server:
  port: 7203

spring:
  application:
    name: taskservice
  boot:
    admin:
      client:
        url: http://localhost:7207
  rabbitmq:
    username: hibbaan
    password: hibbaan
    port: '5672'
    host: localhost

  datasource:
    url: jdbc:mysql://localhost:3306/TaskDB
    username: root
    password: hibbaan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

  data:
    elasticsearch:
      cluster-node: localhost:9200
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7201/eureka/



ms:
  rabbit:
    exchange:
      name: myexchange
    queue:
      name: myqueue
    routing:
      name: myrouting

management:
  endpoints.web.exposure.include:
    - '*'
  tracing:
    sampling:
      probability: 1.0