spring:
  application:
    name: notificationservice
  config:
    import: "optional:configserver:http://localhost:7200"

management:
  endpoints.web.exposure.include:
    - '*'
  tracing:
    sampling:
      probability: 1.0
