spring:
  application:
    name: employeeservice
  config:
    import: "optional:configserver:http://localhost:7200"
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE_SERVICE:
        minimum-number-of-calls: '5'
        permitted-number-of-calls-in-half-open-state: '3'
        register-health-indicator: 'true'
        automatic-transition-from-open-to-half-open-enabled: 'true'
        wait-duration-in-open-state: 5s
        sliding-window-size: '10'
        failure-rate-threshold: '50'